:numbered:

== Overview

Adds runtime maven support as required by some RHPAM applications.

Used by the Emergency Response Demo's *Process Service*


== Details

=== Capabilities
This image adds a new */m2/settings.xml* that sets the following:

. <localRepository>/m2/repository</localRepository>


. <mirrors/> 
+
Sets *mirror* to pull from a nexus.
This becomes critical to support the RH-PAM kie-scanner to dynamically pull kjars (with rules) from that nexus.

.. Why not just set *mirror* configs via S2I ?
+
OpenShift's S2I functionality is capable of customizing the maven settings.xml.
+
However, the Jenkins pipelines of ER-Demo (to include the pipeline for the process server) do not use s2i.  Instead, a "binary build" approach is utilized;  ie:  oc start-build helloBuild --follow --from-file=./target/hello.war.  Subsequently, the target container instantiated from this image will create a custom /m2/settings.xm

=== Runtime Environment Variable Requirement

/m2/settings.xml is read when the following system property is set in the runtime container:  

*kie.maven.settings.custom=/m2/settings.xml*



== Build and Push

. $ buildah bud -f Dockerfile -t quay.io/emergencyresponsedemo/ubi8-jdk-11-mvn:0.0.2 .
. $ podman push quay.io/emergencyresponsedemo/ubi8-jdk-11-mvn:0.0.2 
